dgssi_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dgssi') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'changeme') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dgssi') }}"
      schema: public
      threads: 4
